### ISSUE TITLE
Don't work with collection_check_boxes

### ISSUE THREAD

**Issue by araslanov-e** [nathanl/searchlight#22]
```
= form_for(@search, url: search_path) do |f|
  = f.collection_check_boxes(:post, :author_ids, Author.all, :id, :name)
```
after submit none of the selected option is not checked
because id is not converted to an integer

**Comment by nathanl** [comment]
@araslanov-e OK, I see what you mean. I wasn't familiar with this method and had to make a little demonstration for myself.

Yes, it looks like the `value_method` for http://apidock.com/rails/ActionView/Helpers/FormBuilder/collection_check_boxes does not consider `'1'` and `1` to be equal, so you have to use a workaround like you showed. I don't know a better solution right now, as this is a Rails thing. :) Thanks for documenting the problem and a way to solve it; hopefully others can find this via search if they are dealing with the same thing.
