### ISSUE TITLE
Merge option doesn't seem to work.

### ISSUE THREAD

**Issue by Q-u-y** [nathanl/searchlight#32]
Hi. I wanted to limit the search results  to only ones user allowed to view and I followed the example in the docs, but it seems that the merge option is completely being ignored. I checked the terminal and the option was never added to the query. I even hardcoded it (ex: company_id: 14), but still didn't work. Can you verify if this is a bug or am I doing it wrong? Thanks.

```
class AssetsController < ApplicationController

 def search
    @search = AssetSearch.new(search_params)
    @results = @search.results
  end

private
 def search_params
    (params[:asset_search] || {}).merge(company_id: current_company.id)
  end

 def current_company
    current_user.company
  end

end
```

**Comment by nathanl** [comment]
@Q-u-y Hi! It looks like your `AssetSearch` is getting a hash that includes a `company_id` key, but does it have a `search_company_id` method? If not, it won't do anything with that info.

On the line after you do `AssetSearch.new(search_params)`, try logging the output of `@search.explain`.

**Comment by Q-u-y** [comment]
Thanks for your help Nathan. I did have a `search_company ` method, but when reading the docs, it wasn't too clear to me that I needed to create the method with correct names before I can do merge with it. I thought it will just use the `base_query` with extra conditions. Changing the method to `search_company_id` fixed it.

**Comment by nathanl** [comment]
> I did have a search_company method, but when reading the docs, it wasn't too clear to me that I needed to create the method with correct names before I can do merge with it.

Ah. Sorry about that. If you can see a way to make that clearer, I'd be happy to see a PR.
