### ISSUE TITLE
ActiveRecord - Posibility to merge multiple search methods with OR instead of AND?

### ISSUE THREAD

**Issue by tommyalvarez** [nathanl/searchlight#34]
Is it possible to merge different search methods by OR instead of AND ? Meaning this:

```
def search_some_method
    Post.where(some_column: some_method)
end

def search_some_method_2
    Post.where(another_column: some_method_2)
end
```

Instead of resulting in: 
`Post.where(some_column: some_method).where(another_column: some_method_2) `

results in:
` Post.where(some_column: some_method).or(Post.where(another_column: some_method_2))`

Maybe by sending some parameter in the search params to specify joining of "where's" by OR.

**Comment by nathanl** [comment]
If you have a `def name` and a non-blank `:name` parameter comes in, Searchlight will call your `name` method, which can do whatever you like. `:name` could contain a simple string and your method could do the `.or` as you show, or `:name` could contain a hash of data and options that it could interpret.

It's really up to you.

**Comment by tommyalvarez** [comment]
@nathanl I know i can just do one custom method to perform the OR. The problem is that sometimes using a filter in the front end with two fields, with each field targeting a different method in the Search class, you need the condition to be an OR instead of AND. Of course one could target the same method and sending the arguments in an array, but seems to me a little bit of a hack. Moreover it enhances reusability of methods since sometimes in one page you need one of those filters, in another page the other one, and in a third, a combination of the two of them and due to this limitation you need to create a third method in the search class, handle arguments as an array, etc. I don't know, maybe i'm wrong but it couldn't hurt to have the possibility to merge two o more methods by an OR instead of AND.

**Comment by nathanl** [comment]
@tommyalvarez I see what you're saying. However, Searchlight is designed to be ORM-agnostic. Not only does this mean it can be used with ORMs besides ActiveRecord, it also means that I don't have to update it when any given ORM changes things. As long as they support building queries by chaining, we're good. 😄  So I don't want to make a change specifically to support AR's `.or`.

However, I wonder if this would work?

```ruby
class PersonSearch < Searchlight::Search

  def base_query
    Person.all # or `.scoped` for ActiveRecord 3
  end

  def search_first_name
    query.where(first_name: first_name)
  end

  def search_last_name
    query.where(last_name: last_name)
  end

  def name
    # query.where(first_name: name).or(query.where(last_name: name))
    search_last_name.or(search_first_name)
  end
end

PersonSearch.search(name: "James")
```

**Comment by tommyalvarez** [comment]
@nathanl interesting approach haha. Will give it a try and let you know.

**Comment by nathanl** [comment]
@tommyalvarez Any luck?

**Comment by tommyalvarez** [comment]
@nathanl late response sry, leaving for posterity: nope it doesn't, since _search_first_name_ and _search_last_name_ expects the attributes :first_name and _last_name in `PersonSearch.search(search_attributes)` :(. I ended up giving up and defining a third method that does and or query and tweaking the front-end.

**Comment by nathanl** [comment]
Glad you found a solution. 😄
